const lookupTableConfig = [
  {
    name: "section1",
    apiUrl: "/report2_list1",
    columns: [
      { key: 'carbonyear', labelKey: 'carbonyear' },
      { key: 'controlno', labelKey: 'controlno' },
      { key: 'companyname', labelKey: 'companyname' },
      { key: 'taxcode', labelKey: 'taxcode' },
      { key: 'organizationcode', labelKey: 'organizationcode' },
      { key: 'owner', labelKey: 'owner' },
      { key: 'contactname', labelKey: 'contactname' },
      { key: 'tel', labelKey: 'tel' },
      { key: 'email', labelKey: 'email' },
      { key: 'fax', labelKey: 'fax' },
      { key: 'mobile', labelKey: 'mobile' },
      { key: 'industrycode', labelKey: 'industrycode' },
      { key: 'industryname', labelKey: 'industryname' },
      { key: 'reason', labelKey: 'reason' },
      { key: 'accordto', labelKey: 'accordto' },
      { key: 'ispermit', labelKey: 'ispermit' },
      { key: 'institution', labelKey: 'institution' },
      { key: 'comment', labelKey: 'comment' }
    ],
    title: "section1",
    color: "#f5f5f5",
    payload: {
      reportId: "globalReportId",
      orgId: "globalOrgId",
      yearid: "globalYearid",
      year: "globalYear",
      version: "version",
      language: "i18n.language"
    }
  },
  {
    name: "section2",
    apiUrl: "/report2_list2",
    columns: [
      { key: 'certificate', labelKey: 'certificate' },
      { key: 'competent', labelKey: 'competent' },
      { key: 'city', labelKey: 'city' },
      { key: 'area', labelKey: 'area' },
      { key: 'postcode', labelKey: 'postcode' },
      { key: 'neighborhood', labelKey: 'neighborhood' },
      { key: 'village', labelKey: 'village' },
      { key: 'address', labelKey: 'address' },
      { key: 'combinname', labelKey: 'combinname' },
      { key: 'combinname2', labelKey: 'combinname2' },
      { key: 'combinname3', labelKey: 'combinname3' }
    ],
    title: "section2",
    color: "#f5f5f5",
    payload: {
      reportId: "globalReportId",
      orgId: "globalOrgId",
      yearid: "globalYearid",
      year: "globalYear",
      version: "version",
      language: "i18n.language"
    }
  },
  {
    name: "section3",
    apiUrl: "/report2_list3",
    columns: [
      { key: 'processno', labelKey: 'processno' },
      { key: 'processcode', labelKey: 'processcode' },
      { key: 'processname', labelKey: 'processname' },
      { key: 'assetno', labelKey: 'assetno' },
      { key: 'assetcode', labelKey: 'assetcode' },
      { key: 'assetname', labelKey: 'assetname' },
      { key: 'objecttype', labelKey: 'objecttype' },
      { key: 'objectcode', labelKey: 'objectcode' },
      { key: 'objectname', labelKey: 'objectname' },
      { key: 'isbiomess', labelKey: 'isbiomess' },
      { key: 'isdirect', labelKey: 'isdirect' },
      { key: 'scopetype', labelKey: 'scopetype' },
      { key: 'scopesubtype', labelKey: 'scopesubtype' },
      { key: 'hasco2', labelKey: 'hasco2' },
      { key: 'hasch4', labelKey: 'hasch4' },
      { key: 'hasn2o', labelKey: 'hasn2o' },
      { key: 'hashfcs', labelKey: 'hashfcs' },
      { key: 'haspfcs', labelKey: 'haspfcs' },
      { key: 'hassf6', labelKey: 'hassf6' },
      { key: 'hasnf3', labelKey: 'hasnf3' },
      { key: 'ischp', labelKey: 'ischp' },
      { key: 'comment', labelKey: 'comment' }
    ],
    title: "section3",
    color: "#f5f5f5",
    payload: {
      reportId: "globalReportId",
      orgId: "globalOrgId",
      yearid: "globalYearid",
      year: "globalYear",
      version: "version",
      language: "i18n.language"
    }
  },
  {
    name: "section4",
    apiUrl: "/report2_list4",
    columns: [
      { key: 'processno', labelKey: 'processno' },
      { key: 'processcode', labelKey: 'processcode' },
      { key: 'processname', labelKey: 'processname' },
      { key: 'assetno', labelKey: 'assetno' },
      { key: 'assetcode', labelKey: 'assetcode' },
      { key: 'assetname', labelKey: 'assetname' },
      { key: 'objecttype', labelKey: 'objecttype' },
      { key: 'objectcode', labelKey: 'objectcode' },
      { key: 'objectname', labelKey: 'objectname' },
      { key: 'isbiomess', labelKey: 'isbiomess' },
      { key: 'isdirect', labelKey: 'isdirect' },
      { key: 'scopetype', labelKey: 'scopetype' },
      { key: 'scopesubtype', labelKey: 'scopesubtype' },
      { key: 'scope2provider', labelKey: 'scope2provider' },
      { key: 'amount', labelKey: 'amount' },
      { key: 'unitname', labelKey: 'unitname' },
      { key: 'percentage', labelKey: 'percentage' },
      { key: 'otherunit', labelKey: 'otherunit' },
      { key: 'dsname', labelKey: 'dsname' },
      { key: 'dep', labelKey: 'dep' },
      { key: 'measurefreq', labelKey: 'measurefreq' },
      { key: 'measureequip', labelKey: 'measureequip' },
      { key: 'correctionfreq', labelKey: 'correctionfreq' },
      { key: 'emissionmethod', labelKey: 'emissionmethod' },
      { key: 'lhv', labelKey: 'lhv' },
      { key: 'lhvunit', labelKey: 'lhvunit' },
      { key: 'moisturepercentage', labelKey: 'moisturepercentage' },
      { key: 'carbonpercentage', labelKey: 'carbonpercentage' },
      { key: 'comment', labelKey: 'comment' }
    ],
    title: "section4",
    color: "#f5f5f5",
    payload: {
      reportId: "globalReportId",
      orgId: "globalOrgId",
      yearid: "globalYearid",
      year: "globalYear",
      version: "version",
      language: "i18n.language"
    }
  },
  {
    name: "section5",
    apiUrl: "/report2_list5",
    columns: [
      { key: 'processno', labelKey: 'processno' },
      { key: 'processcode', labelKey: 'processcode' },
      { key: 'processname', labelKey: 'processname' },
      { key: 'assetno', labelKey: 'assetno' },
      { key: 'assetcode', labelKey: 'assetcode' },
      { key: 'assetname', labelKey: 'assetname' },
      { key: 'objecttype', labelKey: 'objecttype' },
      { key: 'objectcode', labelKey: 'objectcode' },
      { key: 'objectname', labelKey: 'objectname' },
      { key: 'isbiomess', labelKey: 'isbiomess' },
      { key: 'isdirect', labelKey: 'isdirect' },
      { key: 'scopetype', labelKey: 'scopetype' },
      { key: 'amount', labelKey: 'amount' },
      { key: 'unitname', labelKey: 'unitname' },
      { key: 'percentage', labelKey: 'percentage' },
      { key: 'emissionmethod', labelKey: 'emissionmethod' },
      { key: 'gas', labelKey: 'gas' },
      { key: 'hvfactor', labelKey: 'hvfactor' },
      { key: 'hvunitname', labelKey: 'hvunitname' },
      { key: 'factor', labelKey: 'factor' },
      { key: 'factorunit', labelKey: 'factorunit' },
      { key: 'factorfrom', labelKey: 'factorfrom' },
      { key: 'levelfactor', labelKey: 'levelfactor' },
      { key: 'emissions', labelKey: 'emissions' },
      { key: 'gwp', labelKey: 'GWP' },
      { key: 'co2e', labelKey: 'co2e' },
      { key: 'emissionstotal', labelKey: 'emissionstotal' },
      { key: 'biomesstotal', labelKey: 'biomesstotal' },
      { key: 'emissionpercentage', labelKey: 'emissionpercentage' },
      { key: 'absco2e', labelKey: 'absco2e' }
    ],
    title: "section5",
    color: "#f5f5f5",
    payload: {
      reportId: "globalReportId",
      orgId: "globalOrgId",
      yearid: "globalYearid",
      year: "globalYear",
      version: "version",
      language: "i18n.language"
    }
  },
  {
    name: "section6",
    apiUrl: "/report2_list6",
    columns: [
      { key: 'processno', labelKey: 'processno' },
      { key: 'processcode', labelKey: 'processcode' },
      { key: 'assetno', labelKey: 'assetno' },
      { key: 'assetcode', labelKey: 'assetcode' },
      { key: 'objectcode', labelKey: 'objectcode' },
      { key: 'objectname', labelKey: 'objectname' },
      { key: 'errorlevel', labelKey: 'errorlevel' },
      { key: 'reliability', labelKey: 'reliability' },
      { key: 'correctionlevel', labelKey: 'correctionlevel' },
      { key: 'credibility', labelKey: 'credibility' },
      { key: 'owner', labelKey: 'owner' },
      { key: 'isdirect', labelKey: 'isdirect' },
      { key: 'scopetype', labelKey: 'scopesubtype' },
      { key: 'categoryofds', labelKey: 'catogoryofds' },
      { key: 'errorfactorlevel', labelKey: 'errorlevel2' },
      { key: 'errorleveltotal', labelKey: 'errorleveltotal' },
      { key: 'emissionpercentage', labelKey: 'emissionpercentage' },
      { key: 'scorerange', labelKey: 'scorerange' },
      { key: 'weightavg', labelKey: 'weightavg' }
    ],
    title: "section6",
    color: "#f5f5f5",
    payload: {
      reportId: "globalReportId",
      orgId: "globalOrgId",
      yearid: "globalYearid",
      year: "globalYear",
      version: "version",
      language: "i18n.language"
    }
  },
  {
    name: "section7",
    apiUrl: "/report2_list7",
    columns: [
      { key: 'processno', labelKey: 'processno' },
      { key: 'assetno', labelKey: 'assetno' },
      { key: 'objectcode', labelKey: 'objectcode' },
      { key: 'objectname', labelKey: 'objectname' },
      { key: 'uncertaintydslower', labelKey: 'uncertaintydslower' },
      { key: 'uncertaintydsupper', labelKey: 'uncertaintydsupper' },
      { key: 'datafrom', labelKey: 'datafrom' },
      { key: 'dsdep', labelKey: 'dsdep' },
      { key: 'gas', labelKey: 'gas1' },
      { key: 'co2e', labelKey: 'co2e' },
      { key: 'uncertaintyfactorlower', labelKey: 'uncertaintyfactorlower' },
      { key: 'uncertaintyfactorupper', labelKey: 'uncertaintyfactorupper' },
      { key: 'uncertaintyfactorfrom', labelKey: 'uncertaintyfactorfrom' },
      { key: 'factordep', labelKey: 'factordep' },
      { key: 'uncertaintygaslower', labelKey: 'uncertaintygaslower' },
      { key: 'uncertaintygasupper', labelKey: 'uncertaintygasupper' },
      { key: 'uncertaintyemissionlower', labelKey: 'uncertaintyemissionlower' },
      { key: 'uncertaintyemissionupper', labelKey: 'uncertaintyemissionupper' }
    ],
    title: "section7",
    color: "#f5f5f5",
    payload: {
      reportId: "globalReportId",
      orgId: "globalOrgId",
      yearid: "globalYearid",
      year: "globalYear",
      version: "version",
      language: "i18n.language"
    }
  }
  // Add more APIs easily in the future...
];

export default lookupTableConfig;