name: Build and deploy Next.js app to Azure Web App - icxprd

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      # Upload source needed for runtime (no node_modules)
      - uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: |
            package.json
            package-lock.json
            next.config.js
            .next
            public
            app
            pages
            middleware.ts
            styles
            # add any other folders your app uses at runtime

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      - uses: azure/webapps-deploy@v3
        with:
          app-name: 'icxprd'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_50C11AE1765940BE82E6BFCA42678516 }}
          package: .
